services:
  redis:
    image: redis:latest
    container_name: rust_auth_redis
    restart: always
    ports:
      - "6379:6379"
    mem_limit: 512m
    volumes:
      - redisdata:/data
    env_file:
      - .env
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: rust_auth_redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsightdata:/db
    environment:
      - REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
  postgres:
    image: postgres:latest
    container_name: rust_auth_pg
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata:
  redisdata:
  redisinsightdata:
