services:
  redis:
    image: redis:latest
    container_name: rust_auth_redis
    restart: always
    ports:
      - "6379:6379"
    mem_limit: 512m
    volumes:
      - redisdata:/data
    env_file:
      - .env
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: rust_auth_redis_commander
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
  postgres:
    image: postgres:latest
    container_name: rust_auth_pg
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata:
  redisdata:
